### PR TITLE
Fixes crashing when reverting a model linked to non-existent associate

### PR DESCRIPTION
**Pull request by serge1peshcoff**
Fixes https://github.com/rikkipitt/rails_admin_history_rollback/issues/15

I couldn't figure out how to restore model's associates, instead I added an error handler to action, so when model that links to non-existent model is restored, the action catches an `ActiveRecord::InvalidForeignKey` error and displays to user that the model cannot be restored. This way, no children are restored, no model itself is restored, but at least this prevents crashing the whole website.
I also added the `admin.history_rollback.rollback_violates_foreign_key` key, to translate this message, and 2 localizations: English and Russian.

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
@rikkipitt Also I've noticed the strange thing when working on this issue: these lines in `history_index.rb`:

```
rescue ActiveRecord::RecordNotFound
    flash[:error] = t 'admin.history_rollback.version_not_found'
    redirect_to :action => :history_index # this line
  rescue ActiveRecord::InvalidForeignKey
    flash[:error] = t 'admin.history_rollback.rollback_violates_foreign_key'
  end

  redirect_to :action => :history_index # and that line
end
```

Here the `redirect_to` is called 2 times, causing an error to appear, because you can't call `redirect_to` or `render` 2 times. I've faced this error while working on this issue, so that's why I didn't include `redirect_to` into `rescue` statement. I didn't fix it, so I guess when the user will get this error, this gem will also crash (I can't reproduce it myself). 
My suggestion is deleting the first `redirect_to` statement, that should fix this.

**Comment by rikkipitt** [comment]
@serge1peshcoff Thanks for taking the time to look into this. Catching the error sounds the best way for now to prevent this crash.

Could you possibly add the new translation (in English) for `history_rollback.zh_cn.yml` please too so it's not missed in that file too please? We can translate it later!

I'll look into those redirects next! Cheers for pointing that out.

Cheers,
Rikki

**Comment by serge1peshcoff** [comment]
Yeah, will add this in a few minutes.

**Comment by rikkipitt** [comment]
Thanks!

**Comment by serge1peshcoff** [comment]
Chinese i18n is missing every key for error displaying, not only mine, so I added them as well.

**Comment by rikkipitt** [comment]
LGTM! Cheers for your help on this. I'll aim to release a new version today. Are you on Rails 4 or 5 by the way?

**Comment by serge1peshcoff** [comment]
Rails 4.2.6

**Pull request merged**
